// Generated with EnemyRoomMap.json. Evaluate within the same age/time as the parent region.
case 9800364LL: return logic->CanUse(RG_LENS_OF_TRUTH) || ctx->GetTrickOption(RT_LENS_SHADOW);
case 9800370LL: return logic->CanUse(RG_ZELDAS_LULLABY);
case 9800371LL: return logic->CanUse(RG_ZELDAS_LULLABY);
case 9800462LL: return logic->CanUse(RG_LENS_OF_TRUTH) || ctx->GetTrickOption(RT_LENS_GANON);
case 9800463LL: return logic->CanUse(RG_LENS_OF_TRUTH) || ctx->GetTrickOption(RT_LENS_GANON);
case 9800464LL: return logic->CanUse(RG_LENS_OF_TRUTH) || ctx->GetTrickOption(RT_LENS_GANON);
case 9800465LL: return logic->CanUse(RG_LENS_OF_TRUTH) || ctx->GetTrickOption(RT_LENS_GANON);
case 9800469LL: return logic->FireTimer() >= 16;
case 9800470LL: return logic->FireTimer() >= 16;
case 9800471LL: return logic->FireTimer() >= 16;
case 9800472LL: return logic->FireTimer() >= 24;
case 9800473LL: return logic->FireTimer() >= 24;
case 9800481LL: return logic->CanUse(RG_FAIRY_BOW) && (logic->CanUse(RG_MIRROR_SHIELD) || logic->SunlightArrows());
case 9800482LL: return logic->CanUse(RG_FAIRY_BOW) && (logic->CanUse(RG_MIRROR_SHIELD) || logic->SunlightArrows());
case 9800483LL: return logic->CanUse(RG_FAIRY_BOW) && (logic->CanUse(RG_MIRROR_SHIELD) || logic->SunlightArrows());
