// Generated by tools/generate_soul_emblems.cjs. Native uploads are 32x32 RGBA32.
#pragma once
#include "align_asset_macro.h"
#include "randomizerEnums.h"
struct SohSoulEmblem { RandomizerGet item; const char* icon; const char* gui; const char* tiles[4]; };
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ENEMY_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ENEMY_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_NPC_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_NPC_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_POT_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_POT_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_CRATE_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_CRATE_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_GRASS_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_GRASS_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ROCK_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ROCK_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_TREE_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_TREE_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_BEEHIVE_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_BEEHIVE_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_SIGN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_SIGN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_COW_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_COW_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_DOG_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_DOG_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FISH_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FISH_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUG_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUG_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_FROG_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_FROG_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ANIMAL_SOUL_HORSE_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ANIMAL_SOUL_HORSE_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_GOHMA_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_GOHMA_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_KING_DODONGO_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_KING_DODONGO_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_BARINADE_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_BARINADE_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_PHANTOM_GANON_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_PHANTOM_GANON_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_VOLVAGIA_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_VOLVAGIA_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_MORPHA_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_MORPHA_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_BONGO_BONGO_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_BONGO_BONGO_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_TWINROVA_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_TWINROVA_SOUL_Tile3";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL_GUI[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL_GUI";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL_Tile0[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL_Tile0";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL_Tile1[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL_Tile1";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL_Tile2[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL_Tile2";
static const ALIGN_ASSET(2) char gSoulEmblem_GANON_SOUL_Tile3[] = "__OTR__textures/parameter_static/gSoulEmblem_GANON_SOUL_Tile3";
static const SohSoulEmblem sSoulEmblems[] = {
    { RG_ENEMY_SOUL, gSoulEmblem_ENEMY_SOUL, gSoulEmblem_ENEMY_SOUL_GUI, { gSoulEmblem_ENEMY_SOUL_Tile0, gSoulEmblem_ENEMY_SOUL_Tile1, gSoulEmblem_ENEMY_SOUL_Tile2, gSoulEmblem_ENEMY_SOUL_Tile3 } },
    { RG_NPC_SOUL, gSoulEmblem_NPC_SOUL, gSoulEmblem_NPC_SOUL_GUI, { gSoulEmblem_NPC_SOUL_Tile0, gSoulEmblem_NPC_SOUL_Tile1, gSoulEmblem_NPC_SOUL_Tile2, gSoulEmblem_NPC_SOUL_Tile3 } },
    { RG_ANIMAL_SOUL, gSoulEmblem_ANIMAL_SOUL, gSoulEmblem_ANIMAL_SOUL_GUI, { gSoulEmblem_ANIMAL_SOUL_Tile0, gSoulEmblem_ANIMAL_SOUL_Tile1, gSoulEmblem_ANIMAL_SOUL_Tile2, gSoulEmblem_ANIMAL_SOUL_Tile3 } },
    { RG_POT_SOUL, gSoulEmblem_POT_SOUL, gSoulEmblem_POT_SOUL_GUI, { gSoulEmblem_POT_SOUL_Tile0, gSoulEmblem_POT_SOUL_Tile1, gSoulEmblem_POT_SOUL_Tile2, gSoulEmblem_POT_SOUL_Tile3 } },
    { RG_CRATE_SOUL, gSoulEmblem_CRATE_SOUL, gSoulEmblem_CRATE_SOUL_GUI, { gSoulEmblem_CRATE_SOUL_Tile0, gSoulEmblem_CRATE_SOUL_Tile1, gSoulEmblem_CRATE_SOUL_Tile2, gSoulEmblem_CRATE_SOUL_Tile3 } },
    { RG_GRASS_SOUL, gSoulEmblem_GRASS_SOUL, gSoulEmblem_GRASS_SOUL_GUI, { gSoulEmblem_GRASS_SOUL_Tile0, gSoulEmblem_GRASS_SOUL_Tile1, gSoulEmblem_GRASS_SOUL_Tile2, gSoulEmblem_GRASS_SOUL_Tile3 } },
    { RG_ROCK_SOUL, gSoulEmblem_ROCK_SOUL, gSoulEmblem_ROCK_SOUL_GUI, { gSoulEmblem_ROCK_SOUL_Tile0, gSoulEmblem_ROCK_SOUL_Tile1, gSoulEmblem_ROCK_SOUL_Tile2, gSoulEmblem_ROCK_SOUL_Tile3 } },
    { RG_TREE_SOUL, gSoulEmblem_TREE_SOUL, gSoulEmblem_TREE_SOUL_GUI, { gSoulEmblem_TREE_SOUL_Tile0, gSoulEmblem_TREE_SOUL_Tile1, gSoulEmblem_TREE_SOUL_Tile2, gSoulEmblem_TREE_SOUL_Tile3 } },
    { RG_BEEHIVE_SOUL, gSoulEmblem_BEEHIVE_SOUL, gSoulEmblem_BEEHIVE_SOUL_GUI, { gSoulEmblem_BEEHIVE_SOUL_Tile0, gSoulEmblem_BEEHIVE_SOUL_Tile1, gSoulEmblem_BEEHIVE_SOUL_Tile2, gSoulEmblem_BEEHIVE_SOUL_Tile3 } },
    { RG_SIGN_SOUL, gSoulEmblem_SIGN_SOUL, gSoulEmblem_SIGN_SOUL_GUI, { gSoulEmblem_SIGN_SOUL_Tile0, gSoulEmblem_SIGN_SOUL_Tile1, gSoulEmblem_SIGN_SOUL_Tile2, gSoulEmblem_SIGN_SOUL_Tile3 } },
    { RG_ANIMAL_SOUL_COW, gSoulEmblem_ANIMAL_SOUL_COW, gSoulEmblem_ANIMAL_SOUL_COW_GUI, { gSoulEmblem_ANIMAL_SOUL_COW_Tile0, gSoulEmblem_ANIMAL_SOUL_COW_Tile1, gSoulEmblem_ANIMAL_SOUL_COW_Tile2, gSoulEmblem_ANIMAL_SOUL_COW_Tile3 } },
    { RG_ANIMAL_SOUL_CUCCO, gSoulEmblem_ANIMAL_SOUL_CUCCO, gSoulEmblem_ANIMAL_SOUL_CUCCO_GUI, { gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile0, gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile1, gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile2, gSoulEmblem_ANIMAL_SOUL_CUCCO_Tile3 } },
    { RG_ANIMAL_SOUL_DOG, gSoulEmblem_ANIMAL_SOUL_DOG, gSoulEmblem_ANIMAL_SOUL_DOG_GUI, { gSoulEmblem_ANIMAL_SOUL_DOG_Tile0, gSoulEmblem_ANIMAL_SOUL_DOG_Tile1, gSoulEmblem_ANIMAL_SOUL_DOG_Tile2, gSoulEmblem_ANIMAL_SOUL_DOG_Tile3 } },
    { RG_ANIMAL_SOUL_FISH, gSoulEmblem_ANIMAL_SOUL_FISH, gSoulEmblem_ANIMAL_SOUL_FISH_GUI, { gSoulEmblem_ANIMAL_SOUL_FISH_Tile0, gSoulEmblem_ANIMAL_SOUL_FISH_Tile1, gSoulEmblem_ANIMAL_SOUL_FISH_Tile2, gSoulEmblem_ANIMAL_SOUL_FISH_Tile3 } },
    { RG_ANIMAL_SOUL_BUG, gSoulEmblem_ANIMAL_SOUL_BUG, gSoulEmblem_ANIMAL_SOUL_BUG_GUI, { gSoulEmblem_ANIMAL_SOUL_BUG_Tile0, gSoulEmblem_ANIMAL_SOUL_BUG_Tile1, gSoulEmblem_ANIMAL_SOUL_BUG_Tile2, gSoulEmblem_ANIMAL_SOUL_BUG_Tile3 } },
    { RG_ANIMAL_SOUL_BUTTERFLY, gSoulEmblem_ANIMAL_SOUL_BUTTERFLY, gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_GUI, { gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile0, gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile1, gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile2, gSoulEmblem_ANIMAL_SOUL_BUTTERFLY_Tile3 } },
    { RG_ANIMAL_SOUL_FROG, gSoulEmblem_ANIMAL_SOUL_FROG, gSoulEmblem_ANIMAL_SOUL_FROG_GUI, { gSoulEmblem_ANIMAL_SOUL_FROG_Tile0, gSoulEmblem_ANIMAL_SOUL_FROG_Tile1, gSoulEmblem_ANIMAL_SOUL_FROG_Tile2, gSoulEmblem_ANIMAL_SOUL_FROG_Tile3 } },
    { RG_ANIMAL_SOUL_HORSE, gSoulEmblem_ANIMAL_SOUL_HORSE, gSoulEmblem_ANIMAL_SOUL_HORSE_GUI, { gSoulEmblem_ANIMAL_SOUL_HORSE_Tile0, gSoulEmblem_ANIMAL_SOUL_HORSE_Tile1, gSoulEmblem_ANIMAL_SOUL_HORSE_Tile2, gSoulEmblem_ANIMAL_SOUL_HORSE_Tile3 } },
    { RG_DEATH_MOUNTAIN_CRATER_BEAN_SOUL, gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL, gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_GUI, { gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile0, gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile1, gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile2, gSoulEmblem_DEATH_MOUNTAIN_CRATER_BEAN_SOUL_Tile3 } },
    { RG_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL, gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL, gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_GUI, { gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile0, gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile1, gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile2, gSoulEmblem_DEATH_MOUNTAIN_TRAIL_BEAN_SOUL_Tile3 } },
    { RG_DESERT_COLOSSUS_BEAN_SOUL, gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL, gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_GUI, { gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile0, gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile1, gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile2, gSoulEmblem_DESERT_COLOSSUS_BEAN_SOUL_Tile3 } },
    { RG_GERUDO_VALLEY_BEAN_SOUL, gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL, gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_GUI, { gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile0, gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile1, gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile2, gSoulEmblem_GERUDO_VALLEY_BEAN_SOUL_Tile3 } },
    { RG_GRAVEYARD_BEAN_SOUL, gSoulEmblem_GRAVEYARD_BEAN_SOUL, gSoulEmblem_GRAVEYARD_BEAN_SOUL_GUI, { gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile0, gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile1, gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile2, gSoulEmblem_GRAVEYARD_BEAN_SOUL_Tile3 } },
    { RG_KOKIRI_FOREST_BEAN_SOUL, gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL, gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_GUI, { gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile0, gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile1, gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile2, gSoulEmblem_KOKIRI_FOREST_BEAN_SOUL_Tile3 } },
    { RG_LAKE_HYLIA_BEAN_SOUL, gSoulEmblem_LAKE_HYLIA_BEAN_SOUL, gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_GUI, { gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile0, gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile1, gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile2, gSoulEmblem_LAKE_HYLIA_BEAN_SOUL_Tile3 } },
    { RG_LOST_WOODS_BRIDGE_BEAN_SOUL, gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL, gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_GUI, { gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile0, gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile1, gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile2, gSoulEmblem_LOST_WOODS_BRIDGE_BEAN_SOUL_Tile3 } },
    { RG_LOST_WOODS_BEAN_SOUL, gSoulEmblem_LOST_WOODS_BEAN_SOUL, gSoulEmblem_LOST_WOODS_BEAN_SOUL_GUI, { gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile0, gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile1, gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile2, gSoulEmblem_LOST_WOODS_BEAN_SOUL_Tile3 } },
    { RG_ZORAS_RIVER_BEAN_SOUL, gSoulEmblem_ZORAS_RIVER_BEAN_SOUL, gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_GUI, { gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile0, gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile1, gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile2, gSoulEmblem_ZORAS_RIVER_BEAN_SOUL_Tile3 } },
    { RG_GOHMA_SOUL, gSoulEmblem_GOHMA_SOUL, gSoulEmblem_GOHMA_SOUL_GUI, { gSoulEmblem_GOHMA_SOUL_Tile0, gSoulEmblem_GOHMA_SOUL_Tile1, gSoulEmblem_GOHMA_SOUL_Tile2, gSoulEmblem_GOHMA_SOUL_Tile3 } },
    { RG_KING_DODONGO_SOUL, gSoulEmblem_KING_DODONGO_SOUL, gSoulEmblem_KING_DODONGO_SOUL_GUI, { gSoulEmblem_KING_DODONGO_SOUL_Tile0, gSoulEmblem_KING_DODONGO_SOUL_Tile1, gSoulEmblem_KING_DODONGO_SOUL_Tile2, gSoulEmblem_KING_DODONGO_SOUL_Tile3 } },
    { RG_BARINADE_SOUL, gSoulEmblem_BARINADE_SOUL, gSoulEmblem_BARINADE_SOUL_GUI, { gSoulEmblem_BARINADE_SOUL_Tile0, gSoulEmblem_BARINADE_SOUL_Tile1, gSoulEmblem_BARINADE_SOUL_Tile2, gSoulEmblem_BARINADE_SOUL_Tile3 } },
    { RG_PHANTOM_GANON_SOUL, gSoulEmblem_PHANTOM_GANON_SOUL, gSoulEmblem_PHANTOM_GANON_SOUL_GUI, { gSoulEmblem_PHANTOM_GANON_SOUL_Tile0, gSoulEmblem_PHANTOM_GANON_SOUL_Tile1, gSoulEmblem_PHANTOM_GANON_SOUL_Tile2, gSoulEmblem_PHANTOM_GANON_SOUL_Tile3 } },
    { RG_VOLVAGIA_SOUL, gSoulEmblem_VOLVAGIA_SOUL, gSoulEmblem_VOLVAGIA_SOUL_GUI, { gSoulEmblem_VOLVAGIA_SOUL_Tile0, gSoulEmblem_VOLVAGIA_SOUL_Tile1, gSoulEmblem_VOLVAGIA_SOUL_Tile2, gSoulEmblem_VOLVAGIA_SOUL_Tile3 } },
    { RG_MORPHA_SOUL, gSoulEmblem_MORPHA_SOUL, gSoulEmblem_MORPHA_SOUL_GUI, { gSoulEmblem_MORPHA_SOUL_Tile0, gSoulEmblem_MORPHA_SOUL_Tile1, gSoulEmblem_MORPHA_SOUL_Tile2, gSoulEmblem_MORPHA_SOUL_Tile3 } },
    { RG_BONGO_BONGO_SOUL, gSoulEmblem_BONGO_BONGO_SOUL, gSoulEmblem_BONGO_BONGO_SOUL_GUI, { gSoulEmblem_BONGO_BONGO_SOUL_Tile0, gSoulEmblem_BONGO_BONGO_SOUL_Tile1, gSoulEmblem_BONGO_BONGO_SOUL_Tile2, gSoulEmblem_BONGO_BONGO_SOUL_Tile3 } },
    { RG_TWINROVA_SOUL, gSoulEmblem_TWINROVA_SOUL, gSoulEmblem_TWINROVA_SOUL_GUI, { gSoulEmblem_TWINROVA_SOUL_Tile0, gSoulEmblem_TWINROVA_SOUL_Tile1, gSoulEmblem_TWINROVA_SOUL_Tile2, gSoulEmblem_TWINROVA_SOUL_Tile3 } },
    { RG_GANON_SOUL, gSoulEmblem_GANON_SOUL, gSoulEmblem_GANON_SOUL_GUI, { gSoulEmblem_GANON_SOUL_Tile0, gSoulEmblem_GANON_SOUL_Tile1, gSoulEmblem_GANON_SOUL_Tile2, gSoulEmblem_GANON_SOUL_Tile3 } },
};
static inline const SohSoulEmblem* SohExtreme_GetSoulEmblem(int item) {
    for (const auto& emblem : sSoulEmblems) if (emblem.item == item) return &emblem;
    return nullptr;
}
