cmake_minimum_required(VERSION 3.26)
foreach(_required IN ITEMS SOH_SOURCE_ROOT SOH_BUILD_ROOT SOH_SHADER_DIR SOH_PACKER SOH_PORT_VERSION)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Missing pack argument: ${_required}")
    endif()
endforeach()
if(NOT EXISTS "${SOH_PACKER}" OR IS_DIRECTORY "${SOH_PACKER}")
    message(FATAL_ERROR "Asset packer executable not found: ${SOH_PACKER}")
endif()
if(NOT IS_DIRECTORY "${SOH_SHADER_DIR}")
    message(FATAL_ERROR "LibUltraShip shader directory not found: ${SOH_SHADER_DIR}")
endif()
file(REAL_PATH "${SOH_SOURCE_ROOT}" _source_root)
file(REAL_PATH "${SOH_BUILD_ROOT}" _build_root)
# Guard deletion below: the staging folder is always inside a distinct build tree.
if(_source_root STREQUAL _build_root)
    message(FATAL_ERROR "Use an out-of-source build directory, such as build-vs.")
endif()
set(_out_dir "${_build_root}/soh")
set(_stage "${_out_dir}/.soh-extreme-assets-stage")
set(_output "${_out_dir}/soh.o2r")
set(_temporary "${_out_dir}/soh.pending.o2r")
file(MAKE_DIRECTORY "${_out_dir}")
file(LOCK "${_out_dir}/soh-extreme-assets.lock" GUARD PROCESS TIMEOUT 120 RESULT_VARIABLE _lock_result)
if(NOT "${_lock_result}" STREQUAL "0")
    message(FATAL_ERROR "Could not lock the asset build: ${_lock_result}")
endif()

set(_inputs "")
set(_input_reals "")
foreach(_input IN ITEMS "${_source_root}/soh/assets/custom" "${_source_root}/assets/custom")
    if(IS_DIRECTORY "${_input}")
        file(REAL_PATH "${_input}" _real)
        if(NOT _real IN_LIST _input_reals)
            list(APPEND _inputs "${_input}")
            list(APPEND _input_reals "${_real}")
        endif()
    endif()
endforeach()
if(NOT _inputs)
    message(FATAL_ERROR "No assets/custom directory in either supported source layout.")
endif()
file(REMOVE_RECURSE "${_stage}")
file(MAKE_DIRECTORY "${_stage}")
# Canonical GitHub assets supply the full base. Legacy root assets are a local
# override, including AP models and textures installed by previous patches.
foreach(_input IN LISTS _inputs)
    message(STATUS "SOH-EXTREME asset input: ${_input}")
    # cmake -E copy_directory always overwrites, even when timestamps match.
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_directory "${_input}" "${_stage}"
                    RESULT_VARIABLE _copy_result)
    if(NOT "${_copy_result}" STREQUAL "0")
        message(FATAL_ERROR "Unable to stage assets from ${_input}")
    endif()
endforeach()
if(NOT IS_DIRECTORY "${_stage}/objects" OR NOT IS_DIRECTORY "${_stage}/textures")
    message(FATAL_ERROR "The combined assets are incomplete (objects/textures missing). Old soh.o2r was preserved.")
endif()
# Only the disposable build-stage shader folder is refreshed.
file(REMOVE_RECURSE "${_stage}/shaders")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_directory "${SOH_SHADER_DIR}" "${_stage}/shaders"
                RESULT_VARIABLE _shader_result)
if(NOT "${_shader_result}" STREQUAL "0")
    message(FATAL_ERROR "Failed to stage LibUltraShip shaders.")
endif()
file(GLOB_RECURSE _resources LIST_DIRECTORIES false "${_stage}/*")
list(LENGTH _resources _resource_count)
message(STATUS "SOH-EXTREME packing ${_resource_count} resource files")
file(REMOVE "${_temporary}")
execute_process(COMMAND "${SOH_PACKER}" "${_stage}" "${_temporary}" "${SOH_PORT_VERSION}"
                RESULT_VARIABLE _pack_result)
if(NOT "${_pack_result}" STREQUAL "0" OR NOT EXISTS "${_temporary}")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "soh-o2r-packer failed (${_pack_result}); old soh.o2r was preserved.")
endif()
file(SIZE "${_temporary}" _size)
if(_size EQUAL 0)
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "soh-o2r-packer wrote an empty archive; old soh.o2r was preserved.")
endif()
file(RENAME "${_temporary}" "${_output}" RESULT _rename_result)
if(NOT "${_rename_result}" STREQUAL "0")
    message(FATAL_ERROR "Unable to replace soh.o2r: ${_rename_result}. Close the game and retry.")
endif()
file(REMOVE_RECURSE "${_stage}")
message(STATUS "SOH-EXTREME asset archive ready: ${_output} (${_size} bytes)")
