"""Export EnBox size by persistent AP ID, including dynamically spawned chests."""
from pathlib import Path
import re
from source_index import native_metadata

ROOT = Path(__file__).resolve().parents[1]
def collect_chests(root=ROOT):
    metadata = native_metadata(root)
    text = (root/'soh/Network/Archipelago/ArchipelagoLocationMap.inc').read_text()
    identities = re.findall(r'static_cast<int>\((RC_\w+)\),\s*(\d+)LL', text)
    result = {}
    for rc, address in identities:
        entry = metadata.get(rc)
        if entry is None or entry['actor'] != 'ACTOR_EN_BOX':
            continue
        # The minigame's static definition carries a check flag, not its spawn
        # params. EnChanger creates both prizes and keys as type 4 chests.
        if rc.startswith('RC_MARKET_TREASURE_CHEST_GAME_'):
            chest_type = 4
        else:
            chest_type = (int(entry['actor_params'], 0) >> 12) & 15
        result[int(address)] = dict(rc=rc, type=chest_type, large=chest_type not in (5, 6, 7, 8))
    return result

if __name__ == '__main__':
    rows = collect_chests()
    source = '# Generated by validation/generate_chest_contract.py from native EnBox identities.\n'
    source += '# Values are native EnBox types; types 5, 6, 7 and 8 are small.\nCHEST_TYPES_BY_AP_ID = {\n'
    source += ''.join(f"    {key}: {row['type']},  # {row['rc']}\n" for key, row in sorted(rows.items()))
    source += '}\n'
    (ROOT/'archipelago/soh_extreme/PhysicalChestTypes.py').write_text(source, encoding='utf-8')
    print('Exported', len(rows), 'physical chest identities')
