"""Generate the client identity/area tables from the AP conversation catalogue.
Run from any directory. Numeric actor IDs come from the checked-in actor table.
"""
from pathlib import Path
import json, re
root = Path(__file__).resolve().parents[1]
catalog = json.loads((root / 'archipelago/soh_extreme/NpcSpeechCatalog.json').read_text(encoding='utf-8'))
actors = {name: int(address, 16) for address, name in re.findall(
    r'/\* (0x[0-9A-Fa-f]+) \*/.*?\b(ACTOR_\w+)',
    (root/'include/tables/actor_table.h').read_text())}
languages = dict(zip(('Deku','Gerudo','Goron','Hylian','Kokiri','Zora','Any'),range(7)))
rows = []
for e in catalog:
    for m in e['matches']:
        actor, scene, mask, value = m[:4]
        room = m[4] if len(m)>4 else -1
        pos = m[5] if len(m)>5 else None
        age = {'child':0,'adult':1}.get(m[6],-1) if len(m)>6 else -1
        rows.append('    { %dLL, %d, %d, %d, %d, %d, %d, %d, %s, %s }, // %s' % (
            e['id'], actors[actor], scene, mask, value, room, age, languages[e['language']],
            'true' if pos else 'false', '{ '+', '.join(map(str,pos or [0,0,0]))+' }', e['name']))
p=root/'soh/Network/Archipelago/NpcSpeechIdentityTable.inc'
p.write_text('// Generated by tools/generate_npc_speech.py; do not renumber IDs.\n'+'\n'.join(rows)+'\n',encoding='utf-8')
# Grotto identity is the native RandomizerCheck; it is never guessed from scene/params.
rows=['    { '+e['native_rc']+', '+str(e['id'])+'LL },' for e in catalog if e.get('native_rc')]
(root/'soh/Network/Archipelago/NpcSpeechScrubs.inc').write_text('\n'.join(rows)+'\n')
areas=['KOKIRI_FOREST','LOST_WOODS','SACRED_FOREST_MEADOW','HYRULE_FIELD','LAKE_HYLIA','GERUDO_VALLEY','GERUDO_FORTRESS','WASTELAND','DESERT_COLOSSUS','MARKET','HYRULE_CASTLE','KAKARIKO_VILLAGE','GRAVEYARD','DEATH_MOUNTAIN_TRAIL','GORON_CITY','DEATH_MOUNTAIN_CRATER','ZORAS_RIVER','ZORAS_DOMAIN','ZORAS_FOUNTAIN','LON_LON_RANCH','DEKU_TREE','DODONGOS_CAVERN','JABU_JABUS_BELLY','FOREST_TEMPLE','FIRE_TEMPLE','WATER_TEMPLE','SPIRIT_TEMPLE','SHADOW_TEMPLE','BOTTOM_OF_THE_WELL','ICE_CAVERN','GERUDO_TRAINING_GROUND','GANONS_CASTLE']
alias={'KF_':0,'LW_':1,'DEKU_THEATER':1,'SFM_':2,'HF_':3,'LH_':4,'GV_':5,'GF_':6,'THIEVES_HIDEOUT':6,'HAUNTED_WASTELAND':7,'WASTELAND_':7,'COLOSSUS_':8,'TEMPLE_OF_TIME':9,'HC_':10,'KAK_':11,'THE_GRAVEYARD':12,'GRAVEYARD_':12,'DEATH_MOUNTAIN_SUMMIT':13,'DMT_':13,'GC_':14,'DMC_':15,'ZR_':16,'ZD_':17,'ZF_':18,'LLR_':19}
def area(region):
    region=region.removeprefix('RR_')
    for prefix,i in alias.items():
        if region.startswith(prefix):return areas[i]
    for a in areas:
        if region.startswith(a):return a
    raise ValueError(region)
rows=[]
for e in catalog:
    regions=[v['region'] for v in e['routes']] or [e['native_region']]
    for a in sorted(set(map(area,regions))):rows.append('    { %dLL, RCAREA_%s },' % (e['id'],a))
(root/'soh/Network/Archipelago/NpcSpeechAreas.inc').write_text('\n'.join(rows)+'\n')
print('Generated',len(catalog),'identities')
