include_guard(GLOBAL)
function(soh_extreme_tlut_safety source_dir)
    file(LOCK "${source_dir}/.soh-extreme-tlut.lock" GUARD FUNCTION TIMEOUT 120)
    set(path "${source_dir}/src/fast/interpreter.cpp")
    file(READ "${path}" cpp)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/SohExtremeTlut.cpp.inc" replacement)
    string(REPLACE "\r\n" "\n" cpp "${cpp}")
    string(REPLACE "\r\n" "\n" replacement "${replacement}")
    string(FIND "${cpp}" "${replacement}" fixed)
    if(NOT fixed EQUAL -1)
        return()
    endif()
    string(FIND "${cpp}" "SOH_EXTREME_TLUT_COMPLETE_GUARD" modified)
    string(FIND "${cpp}" "void Interpreter::GfxDpLoadTlut(" start)
    string(FIND "${cpp}" "void Interpreter::GfxDpLoadBlock(" finish)
    if(NOT modified EQUAL -1 OR start LESS 0 OR finish LESS start)
        message(FATAL_ERROR "SOH-EXTREME: unrecognized TLUT implementation; renderer was not overwritten.")
    endif()
    math(EXPR length "${finish} - ${start}")
    string(SUBSTRING "${cpp}" ${start} ${length} original)
    string(REGEX REPLACE "[ \t\n\r]" "" fingerprint "${original}")
    string(SHA256 fingerprint "${fingerprint}")
    # Reviewed staging implementation, with or without its earlier partial guard.
    if(NOT fingerprint STREQUAL "c47cc929857f14a0514bf7d4123528dce88e670996945316d55eb1cbf92c660f"
       AND NOT fingerprint STREQUAL "a2c21fc46c2acbee751706636c309b01006656addeefe036aaa3edbfed7a447c")
        message(FATAL_ERROR "SOH-EXTREME: TLUT source differs from the reviewed revision; nothing was overwritten.")
    endif()
    string(SUBSTRING "${cpp}" 0 ${start} prefix)
    string(SUBSTRING "${cpp}" ${finish} -1 suffix)
    set(cpp "${prefix}${replacement}\n${suffix}")
    if(NOT cpp MATCHES "#include <[Ww]indows.h>")
        string(PREPEND cpp "#ifdef _WIN32\n#ifndef NOMINMAX\n#define NOMINMAX\n#endif\n#include <windows.h>\n#endif\n")
    endif()
    file(WRITE "${path}" "${cpp}")
    message(STATUS "SOH-EXTREME: complete TLUT source/bounds guard installed")
endfunction()
get_target_property(soh_extreme_lus_source libultraship SOURCE_DIR)
get_filename_component(soh_extreme_lus_root "${soh_extreme_lus_source}" DIRECTORY)
soh_extreme_tlut_safety("${soh_extreme_lus_root}")
