include_guard(GLOBAL)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/SohExtremeVertexEdits.json"
    "${CMAKE_CURRENT_LIST_DIR}/SohExtremeVertexGuard.cpp.inc"
    "${CMAKE_CURRENT_LIST_DIR}/SohExtremeSegmentGuard.cpp.inc"
    "${CMAKE_CURRENT_LIST_DIR}/SohExtremeGfxStep.cpp.inc")
function(soh_extreme_vertex_safety source_dir)
    file(LOCK "${source_dir}/.soh-extreme-vertex.lock" GUARD FUNCTION TIMEOUT 120)
    set(path "${source_dir}/src/fast/interpreter.cpp")
    file(READ "${path}" cpp)
    string(REPLACE "\r\n" "\n" cpp "${cpp}")
    set(original "${cpp}")
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/SohExtremeVertexEdits.json" edits)
    string(JSON count LENGTH "${edits}")
    math(EXPR last "${count} - 1")
    foreach(i RANGE 0 ${last})
        string(JSON before GET "${edits}" ${i} before)
        string(JSON after GET "${edits}" ${i} after)
        string(JSON fragment ERROR_VARIABLE no_fragment GET "${edits}" ${i} fragment)
        if(NOT no_fragment)
            file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${fragment}" body)
            string(REPLACE "\r\n" "\n" body "${body}")
            string(REPLACE "@FRAGMENT@" "${body}" after "${after}")
        endif()
        string(FIND "${cpp}" "${after}" fixed)
        if(NOT fixed EQUAL -1)
            continue()
        endif()
        if(NOT no_fragment)
            string(REGEX MATCH "^[^\n]+" marker "${body}")
            string(FIND "${cpp}" "${marker}" modified)
            if(NOT modified EQUAL -1)
                message(FATAL_ERROR "SOH-EXTREME: altered vertex guard ${i}; nothing was overwritten.")
            endif()
        endif()
        string(FIND "${cpp}" "${before}" start)
        if(start LESS 0)
            message(FATAL_ERROR "SOH-EXTREME: unrecognized vertex renderer edit ${i}; nothing was overwritten.")
        endif()
        string(LENGTH "${before}" length)
        math(EXPR finish "${start} + ${length}")
        string(SUBSTRING "${cpp}" ${finish} -1 suffix)
        string(FIND "${suffix}" "${before}" duplicate)
        if(NOT duplicate EQUAL -1)
            message(FATAL_ERROR "SOH-EXTREME: ambiguous vertex renderer edit ${i}; nothing was overwritten.")
        endif()
        string(SUBSTRING "${cpp}" 0 ${start} prefix)
        set(cpp "${prefix}${after}${suffix}")
    endforeach()
    # Commit only after every reviewed edit matched, so failures are atomic.
    if(NOT cpp STREQUAL original)
        file(WRITE "${path}" "${cpp}")
        message(STATUS "SOH-EXTREME: vertex bounds and malformed graphics frame guards installed")
    endif()
endfunction()
get_target_property(soh_extreme_vertex_source libultraship SOURCE_DIR)
get_filename_component(soh_extreme_vertex_root "${soh_extreme_vertex_source}" DIRECTORY)
soh_extreme_vertex_safety("${soh_extreme_vertex_root}")
