include_guard(GLOBAL)
function(soh_extreme_crash_stack source_dir)
    set(path "${source_dir}/src/ship/debug/CrashHandler.cpp")
    file(READ "${path}" cpp)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/SohExtremeCrashStack.cpp.inc" replacement)
    string(REPLACE "\r\n" "\n" cpp "${cpp}")
    string(REPLACE "\r\n" "\n" replacement "${replacement}")
    string(FIND "${cpp}" "${replacement}" fixed)
    if(NOT fixed EQUAL -1)
        return()
    endif()
    string(FIND "${cpp}" "void CrashHandler::PrintStack(CONTEXT* ctx)" start)
    string(FIND "${cpp}" "extern \"C\" LONG WINAPI seh_filter" finish)
    if(start LESS 0 OR finish LESS start)
        message(FATAL_ERROR "SOH-EXTREME: unrecognized crash stack implementation; not overwritten")
    endif()
    math(EXPR length "${finish} - ${start}")
    string(SUBSTRING "${cpp}" ${start} ${length} original)
    string(REGEX REPLACE "[ \t\n\r]" "" fingerprint "${original}")
    string(SHA256 fingerprint "${fingerprint}")
    if(NOT fingerprint STREQUAL "88c6356c8cee175688e8d32b4070d6b594840d2c5f1af58ba86da7771d1e806d")
        message(FATAL_ERROR "SOH-EXTREME: crash stack source differs from reviewed revision; not overwritten")
    endif()
    string(SUBSTRING "${cpp}" 0 ${start} prefix)
    string(SUBSTRING "${cpp}" ${finish} -1 suffix)
    file(WRITE "${path}" "${prefix}${replacement}\n\n${suffix}")
    message(STATUS "SOH-EXTREME: raw Windows crash addresses enabled")
endfunction()
get_target_property(soh_extreme_crash_source libultraship SOURCE_DIR)
get_filename_component(soh_extreme_crash_root "${soh_extreme_crash_source}" DIRECTORY)
soh_extreme_crash_stack("${soh_extreme_crash_root}")
